// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "version": string;
      "lint.onAdded": boolean;
      "lint.onGroup": boolean;
      "lint.notify": boolean;
      "lint.numConcurrent": number;
      "richtext.toolBar": boolean;
      "richtext.hotkey": boolean;
      "richtext.preview": boolean;
      "rule.no-item-duplication": boolean;
      "rule.no-article-webpage": boolean;
      "rule.no-journal-preprint": boolean;
      "rule.no-value-nullish": boolean;
      "rule.no-title-trailing-dot": boolean;
      "rule.no-doi-prefix": boolean;
      "rule.no-issue-extra-zeros": boolean;
      "rule.no-pages-extra-zeros": boolean;
      "rule.no-volume-extra-zeros": boolean;
      "rule.require-language": boolean;
      "rule.require-language.only": boolean;
      "rule.require-language.only.cmn": boolean;
      "rule.require-language.only.eng": boolean;
      "rule.require-language.only.other": string;
      "rule.require-short-title": boolean;
      "rule.require-journal-abbr": boolean;
      "rule.require-journal-abbr.infer": boolean;
      "rule.require-journal-abbr.usefull": boolean;
      "rule.require-journal-abbr.usefullZh": boolean;
      "rule.require-journal-abbr.customDataPath": string;
      "rule.require-university-place": boolean;
      "rule.require-doi": boolean;
      "rule.require-creators": boolean;
      "rule.correct-title-sentence-case": boolean;
      "rule.correct-title-sentence-case.custom-term-path": string;
      "rule.correct-title-chemical-formula": boolean;
      "rule.correct-title-punctuation": boolean;
      "rule.correct-title-punctuation.quotes": boolean;
      "rule.correct-shortTitle-sentence-case": boolean;
      "rule.correct-creators-case": boolean;
      "rule.correct-creators-pinyin": boolean;
      "rule.correct-creators-punctuation": boolean;
      "rule.correct-date-format": boolean;
      "rule.correct-publication-title-alias": boolean;
      "rule.correct-publication-title-case": boolean;
      "rule.correct-pages-connector": boolean;
      "rule.correct-pages-range": boolean;
      "rule.correct-conference-abbr": boolean;
      "rule.correct-thesis-type": boolean;
      "rule.correct-university-punctuation": boolean;
      "rule.correct-doi-long": boolean;
      "rule.correct-edition-numeral": boolean;
      "rule.correct-volume-numeral": boolean;
      "rule.correct-bookTitle-sentence-case": boolean;
      "rule.correct-proceedingsTitle-sentence-case": boolean;
      "rule.correct-extra-order": boolean;
      "cleanExtra": boolean;
      "semanticScholarToken": string;
      "semanticScholarEndpoint": string;
    };
  }
}
