// Auto generated file. Do not modify.
/* eslint-disable */
type ID =
  | "no-item-duplication"
  | "no-article-webpage"
  | "no-journal-preprint"
  | "require-language"
  | "require-title-sentence-case"
  | "no-title-trailing-dot"
  | "correct-creators-case"
  | "correct-creators-pinyin"
  | "correct-data-format"
  | "correct-publication-title"
  | "require-journal-abbr"
  | "no-doi-prefix"
  | "correct-pages-connector"
  | "no-issue-extra-zeros"
  | "no-pages-extra-zeros"
  | "no-volume-extra-zeros"
  | "correct-conference-abbr"
  | "correct-thesis-type"
  | "correct-university"
  | "require-university-place"
  | "tool-title-guillemet"
  | "tool-creators-ext"
  | "tool-set-language"
  | "tool-update-metadata"
