// Auto generated file. Do not modify.
/* eslint-disable */
type ID =
  | "no-duplicate-item"
  | "no-webpage-item"
  | "no-preprint-journal-article"
  | "language-should-correct"
  | "title-should-sentence-case"
  | "no-title-end-dot"
  | "creators-case"
  | "creators-pinyin"
  | "data-should-in-iso-format"
  | "update-publication-title"
  | "journal-abbr-should-correct"
  | "no-doi-prefix"
  | "pages-connector"
  | "no-extra-zeros-in-issue"
  | "no-extra-zeros-in-pages"
  | "no-extra-zeros-in-volume"
  | "conference-abbr-should-correct"
  | "thesis-type-name"
  | "university"
  | "no-empty-university-place"
  | "title-guillemet"
  | "creators-ext"
  | "language-manual"
  | "update-metadata"
