// Auto generated file. Do not modify.
/* eslint-disable */
type ID =
  | "no-item-duplication"
  | "no-article-webpage"
  | "no-journal-preprint"
  | "no-value-nullish"
  | "require-language"
  | "no-title-trailing-dot"
  | "correct-title-sentence-case"
  | "require-short-title"
  | "correct-shortTitle-sentence-case"
  | "correct-creators-case"
  | "correct-creators-pinyin"
  | "correct-date-format"
  | "require-doi"
  | "no-doi-prefix"
  | "correct-doi-long"
  | "correct-publication-title"
  | "require-journal-abbr"
  | "correct-pages-connector"
  | "no-issue-extra-zeros"
  | "no-pages-extra-zeros"
  | "no-volume-extra-zeros"
  | "correct-conference-abbr"
  | "correct-thesis-type"
  | "correct-university-punctuation"
  | "require-university-place"
  | "correct-edition-numeral"
  | "correct-volume-numeral"
  | "tool-title-guillemet"
  | "tool-creators-ext"
  | "tool-set-language"
  | "tool-update-metadata"
  | "tool-get-short-doi"
