name: Bug report
description: File a bug / issue
title: "[Bug] "
labels:
  - bug
  # - Needs Triage
assignees: northword
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Windows 11 22H2
          - **Zotero Version**: 7.0.0
          - **Addon Version**: 1.0.0
      value: |
        - OS:
        - Zotero Version:
        - Addon Version:
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        If applicable, add screenshots and log to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
