pref("__prefsPrefix__.lint.onAdded", true);
pref("__prefsPrefix__.lint.onGroup", false);
pref("__prefsPrefix__.richtext.toolBar", true);
pref("__prefsPrefix__.richtext.hotkey", true);
pref("__prefsPrefix__.noDuplicationItems", true);
pref("__prefsPrefix__.checkWebpage", true);
pref("__prefsPrefix__.titleSentenceCase", true);
pref("__prefsPrefix__.creatorsCase", true);
pref("__prefsPrefix__.lang", true);
pref("__prefsPrefix__.lang.only", true);
pref("__prefsPrefix__.lang.only.cmn", true);
pref("__prefsPrefix__.lang.only.eng", true);
pref("__prefsPrefix__.lang.only.other", "");
pref("__prefsPrefix__.dateISO", true);
pref("__prefsPrefix__.publicationTitleCase", true);
pref("__prefsPrefix__.abbr", true);
// pref("__prefsPrefix__.abbr.type", "ISO4dot");
pref("__prefsPrefix__.abbr.infer", true);
pref("__prefsPrefix__.abbr.usefull", false);
pref("__prefsPrefix__.abbr.usefullZh", false);
pref("__prefsPrefix__.abbr.customDataPath", "");
pref("__prefsPrefix__.noExtraZeros", true);
pref("__prefsPrefix__.noDOIPrefix", true);
pref("__prefsPrefix__.universityPlace", true);
pref("__prefsPrefix__.cleanExtra", false);
// pref("__prefsPrefix__.richtext.isEnableChem", true);
// pref("__prefsPrefix__.lintAfterRetriveByDOI", true);
